services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:supamenu@db:5432/supamenu?schema=public
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kdsean@12.
      - POSTGRES_DB=supamenu
      - DATABASE_URL=postgresql://postgres:supamenu@db:5432/supamenu?schema=public
      - PORT=3000
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: